### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by sgs98** [runrab/bpmn-vue#1]
![image](https://github.com/runrab/bpmn-vue/assets/54896296/35f324cc-4749-47c3-8c80-1cb9613e99a8)

**Comment by runrab** [comment]
你重新拉下，这是效果预览  地址https://bpmn-vue.vercel.app/

**Comment by sgs98** [comment]
老哥拉完还是一样的问题，你用的是node几

**Comment by sgs98** [comment]
看了示例没有会签是吧

**Comment by sgs98** [comment]
![image](https://github.com/runrab/bpmn-vue/assets/54896296/2e77772c-42e9-45ee-b204-cc1c0d82f455)

**Comment by runrab** [comment]
node 版本:  v16.14.2  
会签实现需要结合后端，单前端没什么意义，将当前节点需要设置为并行用户任务或者串行。

使用github的codespace试试 https://github.com/codespaces  
<img width="1278" alt="截屏2023-08-29 09 40 07" src="https://github.com/runrab/bpmn-vue/assets/51315711/53fe1b5a-0b9b-4e60-aef7-b64b11079e32"> 

这里例子，通过后端发起流程或者上个节点完成任务的时候传一个userList为List类型即可,
<img width="1280" alt="截屏2023-08-29 09 47 58" src="https://github.com/runrab/bpmn-vue/assets/51315711/51e5c214-3688-4663-a3e4-3bf27fcbb84e">

**Comment by runrab** [comment]
推荐使用 [bpmn-process-designer](https://github.com/miyuesc/bpmn-process-designer)

**Comment by sgs98** [comment]
哦找到了配置会签的地方 ，后端我都晓得，目前用v2的设计器也是集成的别人的，v3的没有好使的 我不太会改这个bpmn.js

**Comment by sgs98** [comment]
所以v3用的原生的flowable的设计器 ，有点丑，你这个可以的话想放到开源项目使用

**Comment by runrab** [comment]
可以，本身bpmn.js就是开源的，而且这只是一个很简单的demo，我这个好像也是从一个开源demo的上面拉下来的，我简单修改了一下。
本身bpmn.js就是开源的，看代码就知道我这个就是个空壳子，我自己做了一些扩展，不过是为公司写的，但是并未更新到上面，因为我不是一个前端。
<img width="1279" alt="截屏2023-08-29 10 54 02" src="https://github.com/runrab/bpmn-vue/assets/51315711/af827ed6-1c00-4416-9b15-b0cd76e1b83f">
<img width="1280" alt="截屏2023-08-29 10 54 12" src="https://github.com/runrab/bpmn-vue/assets/51315711/7bddc521-31d2-489b-8c81-6f639a6fdc2e">

**Comment by sgs98** [comment]
我也不是前端 哈哈，不太会改这玩意，现在弄的v3项目还是搞的v2的bpmn.js打包后用ifream引入的
