### ISSUE TITLE
bpmn依赖问题

### ISSUE THREAD

**Issue by Hui-cx** [runrab/bpmn-vue#3]
您好,我安装后会出现依赖问题,我看了一下路径确实没有相关依赖
<img width="920" alt="image" src="https://github.com/runrab/bpmn-vue/assets/93477506/65b11ce1-fff1-4f57-92f5-554f3bfce808">
请问,您能跑起来吗

**Comment by Hui-cx** [comment]
找到原因了,需要单独安装一个插件
<img width="535" alt="image" src="https://github.com/runrab/bpmn-vue/assets/93477506/a03bd31e-f14d-4a29-85b6-d021156e3858">

**Comment by runrab** [comment]
个人并未使用vue版本，而是在react上封状的组件，可能后续考虑增加一些功能，封装成vue组件不再处理
